-- 코드를 입력하세요
# SELECT DISTINCT(C.CAR_ID), C.CAR_TYPE, CEILING(C.DAILY_FEE *(1-0.01*P.DISCOUNT_RATE)*30) FEE
# FROM CAR_RENTAL_COMPANY_CAR C RIGHT OUTER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
# USING (CAR_ID) LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
# USING(CAR_TYPE)
# WHERE C.CAR_TYPE IN ('세단','SUV') AND
# C.CAR_ID NOT IN(
# SELECT CAR_ID
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01') AND
# P.DURATION_TYPE = '30일 이상'
# HAVING FEE BETWEEN 500000 AND 2000000-1
# ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC

SELECT CAR_ID,CAR_TYPE,FLOOR(C.DAILY_FEE*(1-S.DISCOUNT_RATE*0.01) *30) FEE
FROM (SELECT *
FROM CAR_RENTAL_COMPANY_CAR
WHERE (CAR_TYPE = '세단' OR CAR_TYPE = 'SUV') AND CAR_ID NOT IN(
SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE <='2022-11-30' AND END_DATE >= '2022-11-01')) C
JOIN 
(SELECT *
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
WHERE DURATION_TYPE = '30일 이상') S
USING(CAR_TYPE)
WHERE C.DAILY_FEE*(1-S.DISCOUNT_RATE*0.01) *30  BETWEEN 500000 AND 2000000-1
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC










