-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH,COUNT(DISTINCT USER_ID)PUCHASED_USERS , ROUND(COUNT(DISTINCT USER_ID) / (SELECT COUNT(*)
FROM USER_INFO
WHERE JOINED LIKE '2021%'),1) PUCHASED_RATIO
FROM ONLINE_SALE S JOIN (
SELECT USER_ID
FROM USER_INFO
WHERE JOINED LIKE '2021%'
) U
USING(USER_ID)
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE)