# -- 코드를 입력하세요

WITH RECURSIVE TIME AS(
    SELECT 0 HOUR
    UNION ALL
    SELECT HOUR+1
    FROM TIME
    WHERE HOUR<23
)

SELECT T.HOUR HOUR, COUNT(A.ANIMAL_ID) COUNT
FROM TIME T LEFT JOIN ANIMAL_OUTS A
ON T.HOUR = HOUR(DATETIME)
GROUP BY T.HOUR
ORDER BY HOUR