-- 코드를 입력하세요
# SELECT P.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE,'%Y-%m-%d') REVIEW_DATE
# FROM MEMBER_PROFILE P RIGHT OUTER JOIN REST_REVIEW R
# USING (MEMBER_ID)
# WHERE R.MEMBER_ID = (
# SELECT MEMBER_ID
# FROM REST_REVIEW
# GROUP BY MEMBER_ID
# ORDER BY COUNT(MEMBER_ID) DESC
# LIMIT 1
# )
# ORDER BY R.REVIEW_DATE,R.REVIEW_TEXT


SELECT P.MEMBER_NAME,R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE,'%Y-%m-%d') REVIEW_DATE
FROM MEMBER_PROFILE P RIGHT JOIN REST_REVIEW R
USING(MEMBER_ID)
WHERE P.MEMBER_ID = (SELECT MEMBER_ID
                    FROM REST_REVIEW
                    GROUP BY MEMBER_ID
                    ORDER BY COUNT(*) DESC
                    LIMIT 1
                    )
ORDER BY REVIEW_DATE, REVIEW_TEXT











