-- 코드를 작성해주세요
SELECT D.DEPT_ID, D.DEPT_NAME_EN, E.AVG_SAL
FROM (SELECT DEPT_ID, ROUND(AVG(SAL),0) AVG_SAL
FROM HR_EMPLOYEES
GROUP BY DEPT_ID)
E JOIN HR_DEPARTMENT D
USING(DEPT_ID)
ORDER BY E.AVG_SAL DESC